### ISSUE TITLE
Assets

### ISSUE THREAD

**Issue by r-miyamae** [CryptocurrencyApp/CoinpocketServer#2]

**Comment by gatchan0807** [comment]
POST実装 DONE
b40c67a900d859b810a65059f8186dff8b408660

**Comment by gatchan0807** [comment]
GET実装 一部完了
2abc6b9c30635fd86eb1cc6380d33c33ab9c3411

残るはJPYの価格取得の実装

**Comment by gatchan0807** [comment]
GET実装 DONE
b6c2e3b9dcac9744df2a38a5ae842414e9485228

**Comment by gatchan0807** [comment]
後はPUTとDELETE

**Comment by gatchan0807** [comment]
TODO: POST時にCoinIDダブるのを防ぐ処理を書く

**Comment by gatchan0807** [comment]
PUT実装 DONE
7c2d2ba62a0ef7eed7b8b2f615ba2aa26d1f211e

**Comment by gatchan0807** [comment]
DELETE実装 DONE
7f4b2856b102abf4f07222e56107429b7c5b05d4

**Comment by gatchan0807** [comment]
TODOの消化 DONE 
5dde673b87b9825599f77efb26e3768d2bf7aecc
